<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ef5b0266-27cb-4805-ad3b-0798c8cc1500</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Aspiring.Tests" />
    <InternalsVisibleTo Include="Aspiring.Tests.Ingestion" />
    
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.AI" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" />
    <PackageReference Include="PdfPig" />
    <PackageReference Include="System.Linq.Async" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aspiring.ServiceDefaults\Aspiring.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
